name: Build RBrowser for Windows, Mac, and Linux

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build

      - name: Package with electron-builder
        run: npx electron-builder --$RUNNER_OS

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RBrowser-${{ matrix.os }}
          path: dist/*
